export {default as HomePanel} from './HomePanel'
export {default as AddProductsPanel} from './AddProductsPanel'
export {default as EditProductsPanel} from './EditProductsPanel'
export {default as OrdersPanel} from './OrdersPanel'
export {default as CustomersPanel} from './CustomersPanel'